language: c
  
before_install:
  - sudo apt-get update -qq > /dev/null
  - sudo apt-get install -qq mono-devel > /dev/null
  - mozroots --import --sync
  
env:
  - EnableNuGetPackageRestore=true
 
script:
  - xbuild CI.csproj