//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU.Enisey.Contract.ApplicationInquiryNotifierPortType12
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/1.2", ConfigurationName="GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifie" +
        "rPortType12")]
    public interface ApplicationInquiryNotifierPortType12
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией notifyApplicationSubmitted не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:notifyApplicationSubmitted", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse1 notifyApplicationSubmitted(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией notifyApplicationState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:notifyApplicationState", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse1 notifyApplicationState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией notifyInquiryState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:notifyInquiryState", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse1 notifyInquiryState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyApplicationSubmittedRequest
    {
        
        private applicationInfoType applicationInfoField;
        
        private applicationContentInfoType applicationContentField;
        
        private serviceType serviceField;
        
        private serviceOptionType[] serviceOptionListField;
        
        private departmentType departmentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public applicationInfoType applicationInfo
        {
            get
            {
                return this.applicationInfoField;
            }
            set
            {
                this.applicationInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public applicationContentInfoType applicationContent
        {
            get
            {
                return this.applicationContentField;
            }
            set
            {
                this.applicationContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public serviceType service
        {
            get
            {
                return this.serviceField;
            }
            set
            {
                this.serviceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("serviceOption", Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2", IsNullable=false)]
        public serviceOptionType[] serviceOptionList
        {
            get
            {
                return this.serviceOptionListField;
            }
            set
            {
                this.serviceOptionListField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public departmentType department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-types/aq/1.2")]
    public partial class applicationInfoType
    {
        
        private string applicationIDField;
        
        private string applicationSourceSystemIDField;
        
        private infoSystemType applicationSourceSystemField;
        
        private applicantInfoType applicantField;
        
        private applicationStateInfoType applicationStateInfoField;
        
        private System.DateTime applicationSubmissionTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string applicationSourceSystemID
        {
            get
            {
                return this.applicationSourceSystemIDField;
            }
            set
            {
                this.applicationSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public infoSystemType applicationSourceSystem
        {
            get
            {
                return this.applicationSourceSystemField;
            }
            set
            {
                this.applicationSourceSystemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public applicantInfoType applicant
        {
            get
            {
                return this.applicantField;
            }
            set
            {
                this.applicantField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public applicationStateInfoType applicationStateInfo
        {
            get
            {
                return this.applicationStateInfoField;
            }
            set
            {
                this.applicationStateInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public System.DateTime applicationSubmissionTimestamp
        {
            get
            {
                return this.applicationSubmissionTimestampField;
            }
            set
            {
                this.applicationSubmissionTimestampField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class infoSystemType
    {
        
        private string infoSystemCodeField;
        
        private string infoSystemNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string infoSystemCode
        {
            get
            {
                return this.infoSystemCodeField;
            }
            set
            {
                this.infoSystemCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string infoSystemName
        {
            get
            {
                return this.infoSystemNameField;
            }
            set
            {
                this.infoSystemNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.3")]
    public partial class inquiryStateType
    {
        
        private inquiryStateCodeType inquiryStateCodeField;
        
        private string inquiryStateNameField;
        
        private string inquiryStateDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public inquiryStateCodeType inquiryStateCode
        {
            get
            {
                return this.inquiryStateCodeField;
            }
            set
            {
                this.inquiryStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string inquiryStateName
        {
            get
            {
                return this.inquiryStateNameField;
            }
            set
            {
                this.inquiryStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string inquiryStateDescription
        {
            get
            {
                return this.inquiryStateDescriptionField;
            }
            set
            {
                this.inquiryStateDescriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.3")]
    public enum inquiryStateCodeType
    {
        
        /// <remarks/>
        FORMED,
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        RESPONSE_RECEIVED,
        
        /// <remarks/>
        INVALID,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        FAILED_TO_GET_RESPONSE,
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        FAILED_TO_SEND_REQUEST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.3")]
    public partial class inquiryInfoType
    {
        
        private string inquiryTypeNameField;
        
        private string inquiryTypeCodeField;
        
        private string inquiryIDField;
        
        private System.DateTime edgeDateField;
        
        private bool edgeDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryTypeName
        {
            get
            {
                return this.inquiryTypeNameField;
            }
            set
            {
                this.inquiryTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string inquiryTypeCode
        {
            get
            {
                return this.inquiryTypeCodeField;
            }
            set
            {
                this.inquiryTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string inquiryID
        {
            get
            {
                return this.inquiryIDField;
            }
            set
            {
                this.inquiryIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime edgeDate
        {
            get
            {
                return this.edgeDateField;
            }
            set
            {
                this.edgeDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool edgeDateSpecified
        {
            get
            {
                return this.edgeDateFieldSpecified;
            }
            set
            {
                this.edgeDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class errorType
    {
        
        private int executionResultCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int executionResultCode
        {
            get
            {
                return this.executionResultCodeField;
            }
            set
            {
                this.executionResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class tagType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class departmentType
    {
        
        private string departmentIDField;
        
        private string departmentSourceSystemIDField;
        
        private string parentDepartmentIDField;
        
        private string departmentNameField;
        
        private string departmentStatusNameField;
        
        private string departmentTypeNameField;
        
        private string departmentDescriptionField;
        
        private string departmentAddressStringField;
        
        private string oKATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string departmentSourceSystemID
        {
            get
            {
                return this.departmentSourceSystemIDField;
            }
            set
            {
                this.departmentSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string parentDepartmentID
        {
            get
            {
                return this.parentDepartmentIDField;
            }
            set
            {
                this.parentDepartmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string departmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string departmentStatusName
        {
            get
            {
                return this.departmentStatusNameField;
            }
            set
            {
                this.departmentStatusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string departmentTypeName
        {
            get
            {
                return this.departmentTypeNameField;
            }
            set
            {
                this.departmentTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string departmentDescription
        {
            get
            {
                return this.departmentDescriptionField;
            }
            set
            {
                this.departmentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string departmentAddressString
        {
            get
            {
                return this.departmentAddressStringField;
            }
            set
            {
                this.departmentAddressStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OKATO
        {
            get
            {
                return this.oKATOField;
            }
            set
            {
                this.oKATOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class serviceOptionType
    {
        
        private string optionNameField;
        
        private string optionValueNameField;
        
        private string serviceOptionCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string optionName
        {
            get
            {
                return this.optionNameField;
            }
            set
            {
                this.optionNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string optionValueName
        {
            get
            {
                return this.optionValueNameField;
            }
            set
            {
                this.optionValueNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string serviceOptionCode
        {
            get
            {
                return this.serviceOptionCodeField;
            }
            set
            {
                this.serviceOptionCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class serviceType
    {
        
        private string serviceCodeField;
        
        private string serviceRGUCodeField;
        
        private string serviceNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string serviceCode
        {
            get
            {
                return this.serviceCodeField;
            }
            set
            {
                this.serviceCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string serviceRGUCode
        {
            get
            {
                return this.serviceRGUCodeField;
            }
            set
            {
                this.serviceRGUCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string serviceName
        {
            get
            {
                return this.serviceNameField;
            }
            set
            {
                this.serviceNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class contentDataType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("auxiliaryXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("binaryContent", typeof(contentDataTypeBinaryContent), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class contentDataTypeBinaryContent
    {
        
        private string xMLFileNameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XMLFileName
        {
            get
            {
                return this.xMLFileNameField;
            }
            set
            {
                this.xMLFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        XMLContent,
        
        /// <remarks/>
        auxiliaryXMLContent,
        
        /// <remarks/>
        binaryContent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-types/aq/1.2")]
    public partial class applicationContentInfoType
    {
        
        private string applicationContentIDField;
        
        private string namespaceField;
        
        private System.DateTime contentDateTimeField;
        
        private contentDataType contentDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationContentID
        {
            get
            {
                return this.applicationContentIDField;
            }
            set
            {
                this.applicationContentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string @namespace
        {
            get
            {
                return this.namespaceField;
            }
            set
            {
                this.namespaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime contentDateTime
        {
            get
            {
                return this.contentDateTimeField;
            }
            set
            {
                this.contentDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public contentDataType contentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-types/aq/1.2")]
    public partial class applicationStateInfoType
    {
        
        private string applicationStateNameField;
        
        private System.DateTime applicationStateTransitionTimestampField;
        
        private string applicationStateTransitionCommentField;
        
        private string applicationStateCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationStateName
        {
            get
            {
                return this.applicationStateNameField;
            }
            set
            {
                this.applicationStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime applicationStateTransitionTimestamp
        {
            get
            {
                return this.applicationStateTransitionTimestampField;
            }
            set
            {
                this.applicationStateTransitionTimestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string applicationStateTransitionComment
        {
            get
            {
                return this.applicationStateTransitionCommentField;
            }
            set
            {
                this.applicationStateTransitionCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string applicationStateCode
        {
            get
            {
                return this.applicationStateCodeField;
            }
            set
            {
                this.applicationStateCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class organizationInfoType
    {
        
        private string organizationSourceSystemIDField;
        
        private string organizationFullNameField;
        
        private string organizationShortNameField;
        
        private organizationInfoTypeOrganizationDulyAuthorisedSignatory organizationDulyAuthorisedSignatoryField;
        
        private string organizationPhoneField;
        
        private string organizationEmailField;
        
        private string organizationOGRNField;
        
        private string organizationINNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string organizationSourceSystemID
        {
            get
            {
                return this.organizationSourceSystemIDField;
            }
            set
            {
                this.organizationSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string organizationFullName
        {
            get
            {
                return this.organizationFullNameField;
            }
            set
            {
                this.organizationFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string organizationShortName
        {
            get
            {
                return this.organizationShortNameField;
            }
            set
            {
                this.organizationShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public organizationInfoTypeOrganizationDulyAuthorisedSignatory organizationDulyAuthorisedSignatory
        {
            get
            {
                return this.organizationDulyAuthorisedSignatoryField;
            }
            set
            {
                this.organizationDulyAuthorisedSignatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string organizationPhone
        {
            get
            {
                return this.organizationPhoneField;
            }
            set
            {
                this.organizationPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string organizationEmail
        {
            get
            {
                return this.organizationEmailField;
            }
            set
            {
                this.organizationEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string organizationOGRN
        {
            get
            {
                return this.organizationOGRNField;
            }
            set
            {
                this.organizationOGRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string organizationINN
        {
            get
            {
                return this.organizationINNField;
            }
            set
            {
                this.organizationINNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class organizationInfoTypeOrganizationDulyAuthorisedSignatory : personInfoType
    {
        
        private string personPostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string personPost
        {
            get
            {
                return this.personPostField;
            }
            set
            {
                this.personPostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(foreignCitizenInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(individualEntrepreneurInfoType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class personInfoType
    {
        
        private string personSourceSystemIDField;
        
        private string personLastNameField;
        
        private string personFirstNameField;
        
        private string personPatronymicField;
        
        private personInfoTypePersonIdentificationDocument personIdentificationDocumentField;
        
        private string personEmailField;
        
        private string personAddressStringField;
        
        private string phoneField;
        
        private string personSNILSField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string personINNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string personSourceSystemID
        {
            get
            {
                return this.personSourceSystemIDField;
            }
            set
            {
                this.personSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string personLastName
        {
            get
            {
                return this.personLastNameField;
            }
            set
            {
                this.personLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string personFirstName
        {
            get
            {
                return this.personFirstNameField;
            }
            set
            {
                this.personFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string personPatronymic
        {
            get
            {
                return this.personPatronymicField;
            }
            set
            {
                this.personPatronymicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public personInfoTypePersonIdentificationDocument personIdentificationDocument
        {
            get
            {
                return this.personIdentificationDocumentField;
            }
            set
            {
                this.personIdentificationDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string personEmail
        {
            get
            {
                return this.personEmailField;
            }
            set
            {
                this.personEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string personAddressString
        {
            get
            {
                return this.personAddressStringField;
            }
            set
            {
                this.personAddressStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string personSNILS
        {
            get
            {
                return this.personSNILSField;
            }
            set
            {
                this.personSNILSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string personINN
        {
            get
            {
                return this.personINNField;
            }
            set
            {
                this.personINNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class personInfoTypePersonIdentificationDocument
    {
        
        private string identificationDocumentTypeField;
        
        private string identificationDocumentSeriesField;
        
        private string identificationDocumentNumberField;
        
        private System.DateTime identificationDocumentIssueDateField;
        
        private bool identificationDocumentIssueDateFieldSpecified;
        
        private string identificationDocumentIssueIssueAuthorityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificationDocumentType
        {
            get
            {
                return this.identificationDocumentTypeField;
            }
            set
            {
                this.identificationDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificationDocumentSeries
        {
            get
            {
                return this.identificationDocumentSeriesField;
            }
            set
            {
                this.identificationDocumentSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string identificationDocumentNumber
        {
            get
            {
                return this.identificationDocumentNumberField;
            }
            set
            {
                this.identificationDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime identificationDocumentIssueDate
        {
            get
            {
                return this.identificationDocumentIssueDateField;
            }
            set
            {
                this.identificationDocumentIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool identificationDocumentIssueDateSpecified
        {
            get
            {
                return this.identificationDocumentIssueDateFieldSpecified;
            }
            set
            {
                this.identificationDocumentIssueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string identificationDocumentIssueIssueAuthorityName
        {
            get
            {
                return this.identificationDocumentIssueIssueAuthorityNameField;
            }
            set
            {
                this.identificationDocumentIssueIssueAuthorityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class foreignCitizenInfoType : personInfoType
    {
        
        private string citizenshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string citizenship
        {
            get
            {
                return this.citizenshipField;
            }
            set
            {
                this.citizenshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class individualEntrepreneurInfoType : personInfoType
    {
        
        private string oGRNIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OGRNIP
        {
            get
            {
                return this.oGRNIPField;
            }
            set
            {
                this.oGRNIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.2")]
    public partial class applicantInfoType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organizationInfo", typeof(organizationInfoType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("personInfo", typeof(personInfoType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyApplicationSubmittedResponse
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accepted", typeof(tagType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyApplicationSubmittedRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest notifyApplicationSubmittedRequest;
        
        public notifyApplicationSubmittedRequest1()
        {
        }
        
        public notifyApplicationSubmittedRequest1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest notifyApplicationSubmittedRequest)
        {
            this.notifyApplicationSubmittedRequest = notifyApplicationSubmittedRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyApplicationSubmittedResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse notifyApplicationSubmittedResponse;
        
        public notifyApplicationSubmittedResponse1()
        {
        }
        
        public notifyApplicationSubmittedResponse1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse notifyApplicationSubmittedResponse)
        {
            this.notifyApplicationSubmittedResponse = notifyApplicationSubmittedResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyApplicationStateRequest
    {
        
        private string applicationIDField;
        
        private applicationStateInfoType applicationStateInfoField;
        
        private applicationContentInfoType applicationContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public applicationStateInfoType applicationStateInfo
        {
            get
            {
                return this.applicationStateInfoField;
            }
            set
            {
                this.applicationStateInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public applicationContentInfoType applicationContent
        {
            get
            {
                return this.applicationContentField;
            }
            set
            {
                this.applicationContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyApplicationStateResponse
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accepted", typeof(tagType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyApplicationStateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest notifyApplicationStateRequest;
        
        public notifyApplicationStateRequest1()
        {
        }
        
        public notifyApplicationStateRequest1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest notifyApplicationStateRequest)
        {
            this.notifyApplicationStateRequest = notifyApplicationStateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyApplicationStateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse notifyApplicationStateResponse;
        
        public notifyApplicationStateResponse1()
        {
        }
        
        public notifyApplicationStateResponse1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse notifyApplicationStateResponse)
        {
            this.notifyApplicationStateResponse = notifyApplicationStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyInquiryStateRequest
    {
        
        private inquiryInfoType inquiryInfoField;
        
        private inquiryStateType inquiryStateField;
        
        private contentDataType requestContentField;
        
        private contentDataType resultContentField;
        
        private string applicationIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public inquiryInfoType inquiryInfo
        {
            get
            {
                return this.inquiryInfoField;
            }
            set
            {
                this.inquiryInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public inquiryStateType inquiryState
        {
            get
            {
                return this.inquiryStateField;
            }
            set
            {
                this.inquiryStateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public contentDataType requestContent
        {
            get
            {
                return this.requestContentField;
            }
            set
            {
                this.requestContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public contentDataType resultContent
        {
            get
            {
                return this.resultContentField;
            }
            set
            {
                this.resultContentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2")]
    public partial class notifyInquiryStateResponse
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accepted", typeof(tagType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyInquiryStateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest notifyInquiryStateRequest;
        
        public notifyInquiryStateRequest1()
        {
        }
        
        public notifyInquiryStateRequest1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest notifyInquiryStateRequest)
        {
            this.notifyInquiryStateRequest = notifyInquiryStateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class notifyInquiryStateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/application-inquiry-notify/types/1.2", Order=0)]
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse notifyInquiryStateResponse;
        
        public notifyInquiryStateResponse1()
        {
        }
        
        public notifyInquiryStateResponse1(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse notifyInquiryStateResponse)
        {
            this.notifyInquiryStateResponse = notifyInquiryStateResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ApplicationInquiryNotifierPortType12Channel : GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ApplicationInquiryNotifierPortType12Client : System.ServiceModel.ClientBase<GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12>, GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12
    {
        
        public ApplicationInquiryNotifierPortType12Client()
        {
        }
        
        public ApplicationInquiryNotifierPortType12Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public ApplicationInquiryNotifierPortType12Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ApplicationInquiryNotifierPortType12Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public ApplicationInquiryNotifierPortType12Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse1 GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12.notifyApplicationSubmitted(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest1 request)
        {
            return base.Channel.notifyApplicationSubmitted(request);
        }
        
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse notifyApplicationSubmitted(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest notifyApplicationSubmittedRequest)
        {
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest1 inValue = new GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedRequest1();
            inValue.notifyApplicationSubmittedRequest = notifyApplicationSubmittedRequest;
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationSubmittedResponse1 retVal = ((GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12)(this)).notifyApplicationSubmitted(inValue);
            return retVal.notifyApplicationSubmittedResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse1 GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12.notifyApplicationState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest1 request)
        {
            return base.Channel.notifyApplicationState(request);
        }
        
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse notifyApplicationState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest notifyApplicationStateRequest)
        {
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest1 inValue = new GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateRequest1();
            inValue.notifyApplicationStateRequest = notifyApplicationStateRequest;
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyApplicationStateResponse1 retVal = ((GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12)(this)).notifyApplicationState(inValue);
            return retVal.notifyApplicationStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse1 GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12.notifyInquiryState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest1 request)
        {
            return base.Channel.notifyInquiryState(request);
        }
        
        public GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse notifyInquiryState(GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest notifyInquiryStateRequest)
        {
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest1 inValue = new GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateRequest1();
            inValue.notifyInquiryStateRequest = notifyInquiryStateRequest;
            GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.notifyInquiryStateResponse1 retVal = ((GU.Enisey.Contract.ApplicationInquiryNotifierPortType12.ApplicationInquiryNotifierPortType12)(this)).notifyInquiryState(inValue);
            return retVal.notifyInquiryStateResponse;
        }
    }
}
