//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU.Enisey.Contract.AppQuiryPortType101
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/1.0.1", ConfigurationName="GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101")]
    public interface AppQuiryPortType101
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией changeApplicationState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:changeApplicationState", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse1 changeApplicationState(GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией setApplication не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:setApplication", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse1 setApplication(GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getInquiryState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getInquiryState", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse1 getInquiryState(GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией setInquiry не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:setInquiry", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse1 setInquiry(GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией getTargetDepartments не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getTargetDepartments", ReplyAction="")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse1 getTargetDepartments(GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class changeApplicationStateRequest
    {
        
        private string applicationIDField;
        
        private string applicationStateNameField;
        
        private string applicationStateCommentField;
        
        private contentDataType appendContentField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string applicationStateName
        {
            get
            {
                return this.applicationStateNameField;
            }
            set
            {
                this.applicationStateNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string applicationStateComment
        {
            get
            {
                return this.applicationStateCommentField;
            }
            set
            {
                this.applicationStateCommentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public contentDataType appendContent
        {
            get
            {
                return this.appendContentField;
            }
            set
            {
                this.appendContentField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class contentDataType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("auxiliaryXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("binaryContent", typeof(contentDataTypeBinaryContent), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class contentDataTypeBinaryContent
    {
        
        private string xMLFileNameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XMLFileName
        {
            get
            {
                return this.xMLFileNameField;
            }
            set
            {
                this.xMLFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class departmentType
    {
        
        private string departmentIDField;
        
        private string departmentSourceSystemIDField;
        
        private string parentDepartmentIDField;
        
        private string departmentNameField;
        
        private string departmentStatusNameField;
        
        private string departmentTypeNameField;
        
        private string departmentDescriptionField;
        
        private string departmentAddressStringField;
        
        private string oKATOField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string departmentSourceSystemID
        {
            get
            {
                return this.departmentSourceSystemIDField;
            }
            set
            {
                this.departmentSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string parentDepartmentID
        {
            get
            {
                return this.parentDepartmentIDField;
            }
            set
            {
                this.parentDepartmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string departmentName
        {
            get
            {
                return this.departmentNameField;
            }
            set
            {
                this.departmentNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string departmentStatusName
        {
            get
            {
                return this.departmentStatusNameField;
            }
            set
            {
                this.departmentStatusNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string departmentTypeName
        {
            get
            {
                return this.departmentTypeNameField;
            }
            set
            {
                this.departmentTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string departmentDescription
        {
            get
            {
                return this.departmentDescriptionField;
            }
            set
            {
                this.departmentDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string departmentAddressString
        {
            get
            {
                return this.departmentAddressStringField;
            }
            set
            {
                this.departmentAddressStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string OKATO
        {
            get
            {
                return this.oKATOField;
            }
            set
            {
                this.oKATOField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.1")]
    public partial class inquiryStateType
    {
        
        private inquiryStateCodeType inquiryStateCodeField;
        
        private string inquiryStateNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public inquiryStateCodeType inquiryStateCode
        {
            get
            {
                return this.inquiryStateCodeField;
            }
            set
            {
                this.inquiryStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string inquiryStateName
        {
            get
            {
                return this.inquiryStateNameField;
            }
            set
            {
                this.inquiryStateNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.1")]
    public enum inquiryStateCodeType
    {
        
        /// <remarks/>
        FORMED,
        
        /// <remarks/>
        SENDING,
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        RESPONSE_RECEIVED,
        
        /// <remarks/>
        INVALID,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        FAILED_TO_GET_RESPONSE,
        
        /// <remarks/>
        DELETED,
        
        /// <remarks/>
        FAILED_TO_SEND_REQUEST,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry/types/1.1")]
    public partial class inquiryTypeInfoType
    {
        
        private string inquiryTypeNameField;
        
        private string inquiryTypeCodeField;
        
        private int regulatedPeriodField;
        
        private bool regulatedPeriodFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryTypeName
        {
            get
            {
                return this.inquiryTypeNameField;
            }
            set
            {
                this.inquiryTypeNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string inquiryTypeCode
        {
            get
            {
                return this.inquiryTypeCodeField;
            }
            set
            {
                this.inquiryTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int regulatedPeriod
        {
            get
            {
                return this.regulatedPeriodField;
            }
            set
            {
                this.regulatedPeriodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool regulatedPeriodSpecified
        {
            get
            {
                return this.regulatedPeriodFieldSpecified;
            }
            set
            {
                this.regulatedPeriodFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class organizationInfoType
    {
        
        private string organizationSourceSystemIDField;
        
        private string organizationFullNameField;
        
        private string organizationShortNameField;
        
        private organizationInfoTypeOrganizationDulyAuthorisedSignatory organizationDulyAuthorisedSignatoryField;
        
        private string organizationPhoneField;
        
        private string organizationEmailField;
        
        private string organizationOGRNField;
        
        private string organizationINNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string organizationSourceSystemID
        {
            get
            {
                return this.organizationSourceSystemIDField;
            }
            set
            {
                this.organizationSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string organizationFullName
        {
            get
            {
                return this.organizationFullNameField;
            }
            set
            {
                this.organizationFullNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string organizationShortName
        {
            get
            {
                return this.organizationShortNameField;
            }
            set
            {
                this.organizationShortNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public organizationInfoTypeOrganizationDulyAuthorisedSignatory organizationDulyAuthorisedSignatory
        {
            get
            {
                return this.organizationDulyAuthorisedSignatoryField;
            }
            set
            {
                this.organizationDulyAuthorisedSignatoryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string organizationPhone
        {
            get
            {
                return this.organizationPhoneField;
            }
            set
            {
                this.organizationPhoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string organizationEmail
        {
            get
            {
                return this.organizationEmailField;
            }
            set
            {
                this.organizationEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string organizationOGRN
        {
            get
            {
                return this.organizationOGRNField;
            }
            set
            {
                this.organizationOGRNField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string organizationINN
        {
            get
            {
                return this.organizationINNField;
            }
            set
            {
                this.organizationINNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class organizationInfoTypeOrganizationDulyAuthorisedSignatory : personInfoType
    {
        
        private string personPostField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string personPost
        {
            get
            {
                return this.personPostField;
            }
            set
            {
                this.personPostField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(foreignCitizenInfoType))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(individualEntrepreneurInfoType))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class personInfoType
    {
        
        private string personSourceSystemIDField;
        
        private string personLastNameField;
        
        private string personFirstNameField;
        
        private string personPatronymicField;
        
        private personInfoTypePersonIdentificationDocument personIdentificationDocumentField;
        
        private string personEmailField;
        
        private string personAddressStringField;
        
        private string phoneField;
        
        private string personSNILSField;
        
        private System.DateTime birthDateField;
        
        private bool birthDateFieldSpecified;
        
        private string personINNField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string personSourceSystemID
        {
            get
            {
                return this.personSourceSystemIDField;
            }
            set
            {
                this.personSourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string personLastName
        {
            get
            {
                return this.personLastNameField;
            }
            set
            {
                this.personLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string personFirstName
        {
            get
            {
                return this.personFirstNameField;
            }
            set
            {
                this.personFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string personPatronymic
        {
            get
            {
                return this.personPatronymicField;
            }
            set
            {
                this.personPatronymicField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public personInfoTypePersonIdentificationDocument personIdentificationDocument
        {
            get
            {
                return this.personIdentificationDocumentField;
            }
            set
            {
                this.personIdentificationDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string personEmail
        {
            get
            {
                return this.personEmailField;
            }
            set
            {
                this.personEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string personAddressString
        {
            get
            {
                return this.personAddressStringField;
            }
            set
            {
                this.personAddressStringField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string personSNILS
        {
            get
            {
                return this.personSNILSField;
            }
            set
            {
                this.personSNILSField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=9)]
        public System.DateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool birthDateSpecified
        {
            get
            {
                return this.birthDateFieldSpecified;
            }
            set
            {
                this.birthDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string personINN
        {
            get
            {
                return this.personINNField;
            }
            set
            {
                this.personINNField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class personInfoTypePersonIdentificationDocument
    {
        
        private string identificationDocumentTypeField;
        
        private string identificationDocumentSeriesField;
        
        private string identificationDocumentNumberField;
        
        private System.DateTime identificationDocumentIssueDateField;
        
        private bool identificationDocumentIssueDateFieldSpecified;
        
        private string identificationDocumentIssueIssueAuthorityNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string identificationDocumentType
        {
            get
            {
                return this.identificationDocumentTypeField;
            }
            set
            {
                this.identificationDocumentTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string identificationDocumentSeries
        {
            get
            {
                return this.identificationDocumentSeriesField;
            }
            set
            {
                this.identificationDocumentSeriesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string identificationDocumentNumber
        {
            get
            {
                return this.identificationDocumentNumberField;
            }
            set
            {
                this.identificationDocumentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=3)]
        public System.DateTime identificationDocumentIssueDate
        {
            get
            {
                return this.identificationDocumentIssueDateField;
            }
            set
            {
                this.identificationDocumentIssueDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool identificationDocumentIssueDateSpecified
        {
            get
            {
                return this.identificationDocumentIssueDateFieldSpecified;
            }
            set
            {
                this.identificationDocumentIssueDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string identificationDocumentIssueIssueAuthorityName
        {
            get
            {
                return this.identificationDocumentIssueIssueAuthorityNameField;
            }
            set
            {
                this.identificationDocumentIssueIssueAuthorityNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class foreignCitizenInfoType : personInfoType
    {
        
        private string citizenshipField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string citizenship
        {
            get
            {
                return this.citizenshipField;
            }
            set
            {
                this.citizenshipField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class individualEntrepreneurInfoType : personInfoType
    {
        
        private string oGRNIPField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string OGRNIP
        {
            get
            {
                return this.oGRNIPField;
            }
            set
            {
                this.oGRNIPField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class applicantInfoType
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("organizationInfo", typeof(organizationInfoType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("personInfo", typeof(personInfoType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class tagType
    {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1")]
    public partial class errorType
    {
        
        private int executionResultCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int executionResultCode
        {
            get
            {
                return this.executionResultCodeField;
            }
            set
            {
                this.executionResultCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0.1", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        XMLContent,
        
        /// <remarks/>
        auxiliaryXMLContent,
        
        /// <remarks/>
        binaryContent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class changeApplicationStateResponse
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("accepted", typeof(tagType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeApplicationStateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest changeApplicationStateRequest;
        
        public changeApplicationStateRequest1()
        {
        }
        
        public changeApplicationStateRequest1(GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest changeApplicationStateRequest)
        {
            this.changeApplicationStateRequest = changeApplicationStateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class changeApplicationStateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse changeApplicationStateResponse;
        
        public changeApplicationStateResponse1()
        {
        }
        
        public changeApplicationStateResponse1(GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse changeApplicationStateResponse)
        {
            this.changeApplicationStateResponse = changeApplicationStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class setApplicationRequest
    {
        
        private applicantInfoType aplicantInfoField;
        
        private string departmentIDField;
        
        private contentDataType contentDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public applicantInfoType aplicantInfo
        {
            get
            {
                return this.aplicantInfoField;
            }
            set
            {
                this.aplicantInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public contentDataType contentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class setApplicationResponse
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("applicationID", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inquiryType", typeof(inquiryTypeInfoType), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setApplicationRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest setApplicationRequest;
        
        public setApplicationRequest1()
        {
        }
        
        public setApplicationRequest1(GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest setApplicationRequest)
        {
            this.setApplicationRequest = setApplicationRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setApplicationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse setApplicationResponse;
        
        public setApplicationResponse1()
        {
        }
        
        public setApplicationResponse1(GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse setApplicationResponse)
        {
            this.setApplicationResponse = setApplicationResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class getInquiryStateRequest
    {
        
        private string itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("inquiryID", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inquirySourceSystemID", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public string Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName
        {
            get
            {
                return this.itemElementNameField;
            }
            set
            {
                this.itemElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", IncludeInSchema=false)]
    public enum ItemChoiceType
    {
        
        /// <remarks/>
        inquiryID,
        
        /// <remarks/>
        inquirySourceSystemID,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class getInquiryStateResponse
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("contentData", typeof(contentDataType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inquiryStateType", typeof(inquiryStateType), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInquiryStateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest getInquiryStateRequest;
        
        public getInquiryStateRequest1()
        {
        }
        
        public getInquiryStateRequest1(GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest getInquiryStateRequest)
        {
            this.getInquiryStateRequest = getInquiryStateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInquiryStateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse getInquiryStateResponse;
        
        public getInquiryStateResponse1()
        {
        }
        
        public getInquiryStateResponse1(GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse getInquiryStateResponse)
        {
            this.getInquiryStateResponse = getInquiryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class setInquiryRequest
    {
        
        private string inquiryTypeCodeField;
        
        private contentDataType contentDataField;
        
        private string departmentIDField;
        
        private string inquirySourceSystemIDField;
        
        private string applicationIDField;
        
        private string targetDepartmentIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryTypeCode
        {
            get
            {
                return this.inquiryTypeCodeField;
            }
            set
            {
                this.inquiryTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public contentDataType contentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string inquirySourceSystemID
        {
            get
            {
                return this.inquirySourceSystemIDField;
            }
            set
            {
                this.inquirySourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string applicationID
        {
            get
            {
                return this.applicationIDField;
            }
            set
            {
                this.applicationIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string targetDepartmentID
        {
            get
            {
                return this.targetDepartmentIDField;
            }
            set
            {
                this.targetDepartmentIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class setInquiryResponse
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("edgeDate", typeof(System.DateTime), DataType="date", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("inquiryID", typeof(string), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInquiryRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest setInquiryRequest;
        
        public setInquiryRequest1()
        {
        }
        
        public setInquiryRequest1(GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest setInquiryRequest)
        {
            this.setInquiryRequest = setInquiryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInquiryResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse setInquiryResponse;
        
        public setInquiryResponse1()
        {
        }
        
        public setInquiryResponse1(GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse setInquiryResponse)
        {
            this.setInquiryResponse = setInquiryResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class getTargetDepartmentsRequest
    {
        
        private string inquiryTypeCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryTypeCode
        {
            get
            {
                return this.inquiryTypeCodeField;
            }
            set
            {
                this.inquiryTypeCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1")]
    public partial class getTargetDepartmentsResponse
    {
        
        private object[] itemsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("department", typeof(departmentType), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("error", typeof(errorType), Order=0)]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTargetDepartmentsRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest getTargetDepartmentsRequest;
        
        public getTargetDepartmentsRequest1()
        {
        }
        
        public getTargetDepartmentsRequest1(GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest getTargetDepartmentsRequest)
        {
            this.getTargetDepartmentsRequest = getTargetDepartmentsRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getTargetDepartmentsResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/appquiry/req-types/1.0.1", Order=0)]
        public GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse getTargetDepartmentsResponse;
        
        public getTargetDepartmentsResponse1()
        {
        }
        
        public getTargetDepartmentsResponse1(GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse getTargetDepartmentsResponse)
        {
            this.getTargetDepartmentsResponse = getTargetDepartmentsResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AppQuiryPortType101Channel : GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AppQuiryPortType101Client : System.ServiceModel.ClientBase<GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101>, GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101
    {
        
        public AppQuiryPortType101Client()
        {
        }
        
        public AppQuiryPortType101Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AppQuiryPortType101Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AppQuiryPortType101Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AppQuiryPortType101Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse1 GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101.changeApplicationState(GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest1 request)
        {
            return base.Channel.changeApplicationState(request);
        }
        
        public GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse changeApplicationState(GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest changeApplicationStateRequest)
        {
            GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest1 inValue = new GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateRequest1();
            inValue.changeApplicationStateRequest = changeApplicationStateRequest;
            GU.Enisey.Contract.AppQuiryPortType101.changeApplicationStateResponse1 retVal = ((GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101)(this)).changeApplicationState(inValue);
            return retVal.changeApplicationStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse1 GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101.setApplication(GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest1 request)
        {
            return base.Channel.setApplication(request);
        }
        
        public GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse setApplication(GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest setApplicationRequest)
        {
            GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest1 inValue = new GU.Enisey.Contract.AppQuiryPortType101.setApplicationRequest1();
            inValue.setApplicationRequest = setApplicationRequest;
            GU.Enisey.Contract.AppQuiryPortType101.setApplicationResponse1 retVal = ((GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101)(this)).setApplication(inValue);
            return retVal.setApplicationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse1 GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101.getInquiryState(GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest1 request)
        {
            return base.Channel.getInquiryState(request);
        }
        
        public GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse getInquiryState(GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest getInquiryStateRequest)
        {
            GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest1 inValue = new GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateRequest1();
            inValue.getInquiryStateRequest = getInquiryStateRequest;
            GU.Enisey.Contract.AppQuiryPortType101.getInquiryStateResponse1 retVal = ((GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101)(this)).getInquiryState(inValue);
            return retVal.getInquiryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse1 GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101.setInquiry(GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest1 request)
        {
            return base.Channel.setInquiry(request);
        }
        
        public GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse setInquiry(GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest setInquiryRequest)
        {
            GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest1 inValue = new GU.Enisey.Contract.AppQuiryPortType101.setInquiryRequest1();
            inValue.setInquiryRequest = setInquiryRequest;
            GU.Enisey.Contract.AppQuiryPortType101.setInquiryResponse1 retVal = ((GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101)(this)).setInquiry(inValue);
            return retVal.setInquiryResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse1 GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101.getTargetDepartments(GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest1 request)
        {
            return base.Channel.getTargetDepartments(request);
        }
        
        public GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse getTargetDepartments(GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest getTargetDepartmentsRequest)
        {
            GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest1 inValue = new GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsRequest1();
            inValue.getTargetDepartmentsRequest = getTargetDepartmentsRequest;
            GU.Enisey.Contract.AppQuiryPortType101.getTargetDepartmentsResponse1 retVal = ((GU.Enisey.Contract.AppQuiryPortType101.AppQuiryPortType101)(this)).getTargetDepartments(inValue);
            return retVal.getTargetDepartmentsResponse;
        }
    }
}
