//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18051
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GU.Enisey.Contract.InquiryInternalPortType10
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/1.0", ConfigurationName="GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10")]
    public interface InquiryInternalPortType10
    {
        
        // CODEGEN: Контракт генерации сообщений с операцией getInquiryState не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:getInquiryState", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse1 getInquiryState(GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest1 request);
        
        // CODEGEN: Контракт генерации сообщений с операцией setInquiry не является ни RPC, ни упакованным документом.
        [System.ServiceModel.OperationContractAttribute(Action="urn:setInquiry", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse1 setInquiry(GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public partial class getInquiryStateRequest
    {
        
        private string inquiryIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryID
        {
            get
            {
                return this.inquiryIDField;
            }
            set
            {
                this.inquiryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0")]
    public partial class contentDataType
    {
        
        private object[] itemsField;
        
        private ItemsChoiceType[] itemsElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("XMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("auxiliaryXMLContent", typeof(System.Xml.XmlElement), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("binaryContent", typeof(contentDataTypeBinaryContent), Order=0)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemsElementName")]
        public object[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ItemsElementName", Order=1)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemsChoiceType[] ItemsElementName
        {
            get
            {
                return this.itemsElementNameField;
            }
            set
            {
                this.itemsElementNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0")]
    public partial class contentDataTypeBinaryContent
    {
        
        private string xMLFileNameField;
        
        private byte[] valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public string XMLFileName
        {
            get
            {
                return this.xMLFileNameField;
            }
            set
            {
                this.xMLFileNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="base64Binary")]
        public byte[] Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/common-types/aq/1.0", IncludeInSchema=false)]
    public enum ItemsChoiceType
    {
        
        /// <remarks/>
        XMLContent,
        
        /// <remarks/>
        auxiliaryXMLContent,
        
        /// <remarks/>
        binaryContent,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public partial class responseStateInfoType
    {
        
        private responseStateCodeType responseStateCodeField;
        
        private contentDataType contentDataField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public responseStateCodeType responseStateCode
        {
            get
            {
                return this.responseStateCodeField;
            }
            set
            {
                this.responseStateCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public contentDataType contentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public enum responseStateCodeType
    {
        
        /// <remarks/>
        RESULT,
        
        /// <remarks/>
        REJECT,
        
        /// <remarks/>
        INVALID,
        
        /// <remarks/>
        ACCEPT,
        
        /// <remarks/>
        PROCESS,
        
        /// <remarks/>
        FAILURE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public partial class getInquiryStateResponse
    {
        
        private responseStateInfoType responseStateInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public responseStateInfoType responseStateInfo
        {
            get
            {
                return this.responseStateInfoField;
            }
            set
            {
                this.responseStateInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInquiryStateRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0", Order=0)]
        public GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest getInquiryStateRequest;
        
        public getInquiryStateRequest1()
        {
        }
        
        public getInquiryStateRequest1(GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest getInquiryStateRequest)
        {
            this.getInquiryStateRequest = getInquiryStateRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getInquiryStateResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0", Order=0)]
        public GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse getInquiryStateResponse;
        
        public getInquiryStateResponse1()
        {
        }
        
        public getInquiryStateResponse1(GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse getInquiryStateResponse)
        {
            this.getInquiryStateResponse = getInquiryStateResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public partial class setInquiryRequest
    {
        
        private string inquiryTypeCodeField;
        
        private contentDataType contentDataField;
        
        private string departmentIDField;
        
        private string inquirySourceSystemIDField;
        
        private string inquiryIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string inquiryTypeCode
        {
            get
            {
                return this.inquiryTypeCodeField;
            }
            set
            {
                this.inquiryTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public contentDataType contentData
        {
            get
            {
                return this.contentDataField;
            }
            set
            {
                this.contentDataField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string departmentID
        {
            get
            {
                return this.departmentIDField;
            }
            set
            {
                this.departmentIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string inquirySourceSystemID
        {
            get
            {
                return this.inquirySourceSystemIDField;
            }
            set
            {
                this.inquirySourceSystemIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string inquiryID
        {
            get
            {
                return this.inquiryIDField;
            }
            set
            {
                this.inquiryIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0")]
    public partial class setInquiryResponse
    {
        
        private responseStateInfoType responseStateInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public responseStateInfoType responseStateInfo
        {
            get
            {
                return this.responseStateInfoField;
            }
            set
            {
                this.responseStateInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInquiryRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0", Order=0)]
        public GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest setInquiryRequest;
        
        public setInquiryRequest1()
        {
        }
        
        public setInquiryRequest1(GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest setInquiryRequest)
        {
            this.setInquiryRequest = setInquiryRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class setInquiryResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="urn://x-artefacts-it-ru/dob/poltava/inquiry-internal/req-types/1.0", Order=0)]
        public GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse setInquiryResponse;
        
        public setInquiryResponse1()
        {
        }
        
        public setInquiryResponse1(GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse setInquiryResponse)
        {
            this.setInquiryResponse = setInquiryResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InquiryInternalPortType10Channel : GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InquiryInternalPortType10Client : System.ServiceModel.ClientBase<GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10>, GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10
    {
        
        public InquiryInternalPortType10Client()
        {
        }
        
        public InquiryInternalPortType10Client(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public InquiryInternalPortType10Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InquiryInternalPortType10Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public InquiryInternalPortType10Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse1 GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10.getInquiryState(GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest1 request)
        {
            return base.Channel.getInquiryState(request);
        }
        
        public GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse getInquiryState(GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest getInquiryStateRequest)
        {
            GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest1 inValue = new GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateRequest1();
            inValue.getInquiryStateRequest = getInquiryStateRequest;
            GU.Enisey.Contract.InquiryInternalPortType10.getInquiryStateResponse1 retVal = ((GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10)(this)).getInquiryState(inValue);
            return retVal.getInquiryStateResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse1 GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10.setInquiry(GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest1 request)
        {
            return base.Channel.setInquiry(request);
        }
        
        public GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse setInquiry(GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest setInquiryRequest)
        {
            GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest1 inValue = new GU.Enisey.Contract.InquiryInternalPortType10.setInquiryRequest1();
            inValue.setInquiryRequest = setInquiryRequest;
            GU.Enisey.Contract.InquiryInternalPortType10.setInquiryResponse1 retVal = ((GU.Enisey.Contract.InquiryInternalPortType10.InquiryInternalPortType10)(this)).setInquiry(inValue);
            return retVal.setInquiryResponse;
        }
    }
}
